### PR TITLE
Add first lecture

### PR DESCRIPTION
**Pull request by Seth10001**
I added the first lecture! Check it out

### CODE REVIEW

**Review by John-Carr — CHANGES_REQUESTED** [review]
image
Note that the topic within the lecture is at the same heading level as the lecture this should be made one step down in the hierarchy.

**Comment by Seth10001** [comment]
Nice catch! It's fixed @John-Carr

**Review by John-Carr — APPROVED** [review]

**Comment by scuervo101** [comment]
Should we put the video under lectures? Also should I add the written guide to that same tab?

**Comment by Seth10001** [comment]
@scuervo101 It is under lectures now! I think a brief summary would be good

**Pull request merged**
