### PR TITLE
Knowledge Retention Fluid Dynamics

### PR DESCRIPTION
**Pull request by Jwnels5**
Addition of Fluid Dynamics to Knowledge Retention.

### CODE REVIEW

**Review by John-Carr — CHANGES_REQUESTED** [review]
Looks like the image doesn't show up correctly make sure the path specified is where the image stored. Let me know if you cant figure it out (I think the issue might be ./_static/knowledge/powerdrivegraph.PNG)

**Review by scuervo101 — APPROVED** [review]
The image looks to be working for me. Everything looks good, I'll approve, not sure why John can't see the image.

**Review by Seth10001 — CHANGES_REQUESTED** [review]
I can't see the image on the PR build (https://solar-gators-docs--37.org.readthedocs.build/en/37/AeroBody/Body/knowledge.html). I haven't tried it locally

**Review by Seth10001 — APPROVED** [review]
looks good now

**Review by John-Carr — APPROVED** [review]

**Pull request merged**
