### PR TITLE
BMS Changes r2

### PR DESCRIPTION
**Pull request by yashtheboss**
I've added stuff for Orion BMS, and planning to add startup board soon. Let me know how it looks!

### CODE REVIEW

**Comment by Seth10001** [comment]
For some reason, the build failed?

**Comment by yashtheboss** [comment]
Yeah I'm not sure why, the commit right before the last one had it's check pass, I only changed a couple letters after that, do you think it's because I did it after I made the pull request?

**Comment by Seth10001** [comment]
Nah it shouldn't be okay... hmm, not sure how to rerun the build

**Comment by yashtheboss** [comment]
Should I just close this merge request and try to repush or something? It won't delete the stuff if I close it, right?

**Pull request closed without merging**
