### PR TITLE
Add a maintain website guide

### PR DESCRIPTION
**Pull request by Seth10001**
The changes are under electrical on the `Website` link.

### CODE REVIEW

**Comment by John-Carr** [comment]
Task linked: [CU-bwh25p Write docs for maintaining the advertisement website](https://app.clickup.com/t/bwh25p)

**Comment by John-Carr** [comment]
Looks good. Do we want to say documentation for the other endpoints are in the repo for the API?

**Review by John-Carr — COMMENTED** [review]
See above comment.

**Comment by Seth10001** [comment]
@John-Carr Oh are there docs for that? I think if they're admin related we should leave them/make them there for sure

**Review by John-Carr — APPROVED** [review]
I think this is good. We will keep admin API off of the docs.

**Pull request merged**
