### PR TITLE
Solar array edits

### PR DESCRIPTION
**Pull request by cwang2018**
Added Documentation folder and Soldering SOP

### CODE REVIEW

**Comment by cwang2018** [comment]
I didn't check off any of the binary files from my branch this time but I'm not sure if it still shows up on your end? I'm sorry if it still shows up, let me know if there are any other issues too.

**Review by Seth10001 — CHANGES_REQUESTED** [review]
Thank you for contributing to the docs! I have a few changes below.

- There are three `.DS_Store` file that got committed to the docs, can you remove them?
- The toctree's don't appear to be linking correctly. I think there just needs to be extra space at the end of the items. Check out [the docs preview here](https://solar-gators-docs--31.org.readthedocs.build/en/31/AeroBody/SolarArray/index.html)

**Comment by cwang2018** [comment]
Let me know if there's still problems with anything

**Review by Seth10001 — CHANGES_REQUESTED** [review]
Hey, I'm still the toctree on the website?
see here: https://solar-gators-docs--31.org.readthedocs.build/en/31/AeroBody/SolarArray/index.html

**Comment by Seth10001** [comment]
I'm still not seeing the toctreee*

Had a typo above lol

**Comment by cwang2018** [comment]
Thanks for checking in! I haven't tried to fix the issue with the toctree yet because instead of waiting and seeing if my code works when you review it, I'm trying to make livehtml work on my Mac so that I'll know if it works before I waste your time asking you to review it. Right now I'm having trouble getting my livehtml to work, but once I figure it out and fix the index issue, I'll re-request the review from you. Thank you!

**Comment by Seth10001** [comment]
No worries! If you have time to jump on discord tonight around 6pm then I can help you out. Send me a slack message if you don’t have access to discord.

On Oct 22, 2020, at 3:17 PM, cwang2018 <notifications@github.com> wrote:

﻿

Thanks for checking in! I haven't tried to fix the issue with the toctree yet because instead of waiting and seeing if my code works when you review it, I'm trying to make livehtml work on my Mac so that I'll know if it works before I waste your time asking you to review it. Right now I'm having trouble getting my livehtml to work, but once I figure it out and fix the index issue, I'll re-request the review from you. Thank you!

**Comment by cwang2018** [comment]
That'd be great, thank you! My lab ends at 6 so I might be a few minutes late but I'll get on discord as soon as I can.

**Review by Seth10001 — APPROVED** [review]
Looks good!

**Comment by John-Carr** [comment]
@cwang2018 is there anything else you'd like to do with this branch? If not could you go ahead and smash that merge button? :)

**Comment by cwang2018** [comment]
Thank you for reminding me! I forgot I had to merge as the last step

**Pull request merged**
